export const projects = [
  {
    projectKey: "ezygas",
    link: "https://ezygas.co",
    img: "ezygas.png",
    tags: [
      "nextjs",
      "typescript",
      "tailwindcss",
      "django",
      "django rest framework",
      "postgresql",
      "docker",
      "docker compose",
    ],
  },
  {
    projectKey: "sol7",
    img: "sol7.png",
    link: "https://sol7.ai",
    tags: ["nextjs", "typescript", "tailwindcss", "docker", "docker compose"],
  },
  {
    projectKey: "selen",
    link: "https://selen.ai",
    img: "selen.png",
    tags: [
      "nextjs",
      "typescript",
      "tailwindcss",
      "docker",
      "docker compose",
      "sip.js",
      "strapi",
      "longdo map",
    ],
  },
  {
    projectKey: "synapes",
    img: "synapes.png",
    link: "https://synapes.ai",
    tags: ["nextjs", "typescript", "tailwindcss", "docker", "docker compose", "strapi"],
  },
  {
    projectKey: "senergy",
    img: "senergy.png",
    link: "https://senergythailand.com",
    tags: ["gatsbyjs", "typescript", "tailwindcss", "docker", "docker compose"],
  },
];
